import screeninfo
import os
os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "hide"
import pygame as pg

d_config = {
	"OpenWeather_key": "1fae0386a4d15ee5dd547562f9d0dd5c",
    "l_threadsResults": [],
    "l_forecasts": [],
    "label_name": "O Cara do Tempo",
    "window_originalSize": (960, 540),
    "window_resolution": 1,
    "monitor_size": (screeninfo.get_monitors()[0].width, screeninfo.get_monitors()[0].height),
    "window_position": (0, 0),
    "window_icon": None,
    "FPS": 60,
    "background_color": (128, 128, 128),
    "scene": ["load_screen", "scene_0"],
    "scene_state": "",
    "load_scene": False,
    "load_target": 0,
    "d_objects": {},
    "spriteGroup": pg.sprite.LayeredUpdates(),
    "sprites_colorKey": ((253, 77, 211)),
    "dir_root": os.getcwd()[:-8],
    "spriteSheet_0": None,
    "key_f": pg.K_f,
    "key_r": pg.K_r,
    "key_-": pg.K_MINUS,
    "key_0": pg.K_0,
    "key_1": pg.K_1,
    "key_2": pg.K_2,
    "key_3": pg.K_3,
    "key_4": pg.K_4,
    "key_5": pg.K_5,
    "key_6": pg.K_6,
    "key_7": pg.K_7,
    "key_8": pg.K_8,
    "key_9": pg.K_9,
    "key_keypad0": pg.K_KP0,
    "key_keypad1": pg.K_KP1,
    "key_keypad2": pg.K_KP2,
    "key_keypad3": pg.K_KP3,
    "key_keypad4": pg.K_KP4,
    "key_keypad5": pg.K_KP5,
    "key_keypad6": pg.K_KP6,
    "key_keypad7": pg.K_KP7,
    "key_keypad8": pg.K_KP8,
    "key_keypad9": pg.K_KP9,
    "key_backspace": pg.K_BACKSPACE,
    "key_return": pg.K_RETURN,
}